version: '3'

services:
  chef:
    image: polapob/chef-service:1.0
    container_name: chef-service
    ports:
      - 50001:50001
  
  recipe:
    image: polapob/recipe-service:1.0
    container_name: recipe-service
    ports:
      - 50002:50002

  review:
    image: polapob/review-service:1.0
    container_name: review-service
    ports:
      - 50003:50003
